### ISSUE TITLE
Doesn't work on Safari.

### ISSUE THREAD

**Issue by Marcin-TA** [willdurand/Negotiation#103]

**Comment by willdurand** [comment]
What isn't working exactly?

**Comment by Marcin-TA** [comment]
It doesn't detect language. I use version `2.3.1` of the lib. Basically, Safari returns `en-gb` for `$_SERVER['HTTP_ACCEPT_LANGUAGE']`. However, the negociator class throws an exception when I call `getType()` method.

![Screenshot 2019-10-01 at 13 53 41](https://user-images.githubusercontent.com/35221797/65963562-eca1f900-e452-11e9-94c0-70192b87d073.png)

**Comment by Marcin-TA** [comment]
@here For future reference, I recommend to install PHP extension `ext-intl` and use this: https://www.php.net/manual/en/locale.lookup.php

**Comment by willdurand** [comment]
should be fixed by https://github.com/willdurand/Negotiation/pull/113
