### ISSUE TITLE
Create a new release supporting PHP 8

### ISSUE THREAD

**Issue by lazka** [willdurand/Negotiation#109]
It's nice to see #106 adding PHP 8.0 support. Can a new release including these fixes be created?

Thanks!

**Comment by LaVehicle** [comment]
@willdurand friendly ping

**Comment by LordSimal** [comment]
just saying, official PHP 8.0 release is on 26th November 2020, so in 3 days...

**Comment by LordSimal** [comment]
PHP 8.0 is now released
https://www.php.net/archive/2020.php#2020-11-26-3

**Comment by willdurand** [comment]
Please see: https://github.com/willdurand/Negotiation/releases/tag/3.0.0
