### ISSUE TITLE
Order or parameters should be ignored

### ISSUE THREAD

**Issue by neural-wetware** [willdurand/Negotiation#48]
If the order of the parameters in the header is different from the order in the server priority, this library fails to match the priority.

    <?
    use \Negotiation;
    
    include './Negotiation/src/Negotiation/NegotiatorInterface.php' ;
    include './Negotiation/src/Negotiation/Negotiator.php' ;
    include './Negotiation/src/Negotiation/FormatNegotiatorInterface.php' ;
    include './Negotiation/src/Negotiation/FormatNegotiator.php' ;
    include './Negotiation/src/Negotiation/AcceptHeader.php' ;
    
    $neg = new \Negotiation\FormatNegotiator();
    $best = $neg->getBest('text/html; foo=bar; biz=baz', array('text/plain', 'text/html; foo=bar; biz=baz'));
    var_dump($best);
    
    $neg = new \Negotiation\FormatNegotiator();
    $best = $neg->getBest('text/html; foo=bar; biz=baz', array('text/plain', 'text/html; biz=baz; foo=bar'));
    var_dump($best);

I think that the match should still occur regardless of the parameter order.

**Comment by willdurand** [comment]
:+1:

**Comment by neural-wetware** [comment]
To solve this the media type and parameters need to be compared separately, instead of as one string with the media type and params concatenated.

Pull request #47 will allow us to isolate the media type for comparison in the negotiation logic.
