### ISSUE TITLE
support for wildcard priorities

### ISSUE THREAD

**Issue by neural-wetware** [willdurand/Negotiation#49]
The code and unit tests allow for cases where the server sets `*/*` or `something/*` as a priority. I don't think this makes sense and it greatly overcomplicates the negotiation logic.

The server needs to return an actual media type. If the server sets `*/*` as a preference, it could get any media type from bestFit(). Then the server must then manually check if it supports the returned media type, which is supposed to be the job of the library.

It makes more sense for the server to just list all supported media types in the priorities array. These should be actual media types and not media ranges.

I understand that this could break existing clients that are using the library in some esoteric way. Could removing wildcard priorities considered for the new version?

**Comment by willdurand** [comment]
I don't think so to be honest. Supporting ranges is part of the spec..

**Comment by neural-wetware** [comment]
I don't mean to remove support for ranges in the `Accept` header. I'm talking about setting `*/*` as a _priority_. For example in `dataProviderForGetBestFormat()` you have

    array('text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', array('rss', '*/*'), 'rss')

Where `array('rss', '*/*')` is the servers priorities for what media type to produce.

I don't understand the use case for this. It literally means the server is willing to produce _any_ media type. How can that be?

**Comment by willdurand** [comment]
I don't know, but let's put the question the other way around: why not letting users do that?

**Comment by neural-wetware** [comment]
Because it's not the point of the library. It convolutes the negotiation logic for proper use. This makes maintenance more difficult and bugs more likely. Don't put legs on snake.

Would you consider this change for version 2?

**Comment by willdurand** [comment]
I might consider this change, but I'm still not convinced.
