### ISSUE TITLE
change case of parameter keys causes failed match

### ISSUE THREAD

**Issue by neural-wetware** [willdurand/Negotiation#52]
The `sanitize()` function is lower casing the priority parameters, which are [normally](http://www.w3.org/Protocols/rfc1341/4_Content-Type.html) case sensitive. This causes the check in `FormatNegotiator::getBest()` to fail.

    <?
    include('vendor/autoload.php');
    
    use \Negotiation\FormatNegotiator;
    
    $neg = new FormatNegotiator();
    
    $type = 'text/html; charset=UTF-8;';
    $best = $neg->getBest($type, array($type));
    var_dump($best);

**Comment by willdurand** [comment]
It seems that some parameters can be case insensitive though.. Either we do not lower all params or perform the comparison with lowered values on both sides.

**Comment by neural-wetware** [comment]
Or we could do case sensitive match, but hard code exceptions for known 
(registered) type/attributes that aren't sensitive.

**Comment by willdurand** [comment]
I'm fine with that solution too.

**Comment by willdurand** [comment]
Does not apply in Negotiation 2.0 I guess.
