### ISSUE TITLE
[Question] Can you explain further your use of "format" vs. "media type"?

### ISSUE THREAD

**Issue by rszrama** [willdurand/Negotiation#56]
Ever since finding your excellent little library, I've been trying to trace down through the various RFCs and other documentation why you might use "format" instead of "media type". It appears as though formats in practical usage would mostly correspond to a single media type with the "format" in those cases being a helpful shorthand. However, it also appears you're using "format" as a parent term to group multiple similar media types together (e.g. application/javascript + text/javascript).

Were these format groupings purely derived from Symfony's usage, or is there some external resource you were looking at to create them? And are there any best practices for when to use format vs. media-type? Should I as an application developer default to using your libraries format negotiator to avoid having to encode the media type associations you're making my own codebase?

**Comment by willdurand** [comment]
This should be fixed in 2.0. We better stick to the RFC now.

**Comment by rszrama** [comment]
Have you written about the changes in 2.0 anywhere that I can follow (besides the updated README)? Any word on its stability / full release schedule so I know when you'd recommend developers begin using it?

**Comment by willdurand** [comment]
First "alpha" version has been released. It is pretty stable already, but we need feedback and people to test it.

PS: it will be released as stable in a few weeks.
