### ISSUE TITLE
Good practices : create interfaces ?

### ISSUE THREAD

**Issue by Ener-Getick** [willdurand/Negotiation#64]
I think it could a good idea to create a new interface ``NegotiatorInterface`` and to fill ``AcceptHeader`` with the ``BaseAccept`` methods (https://github.com/willdurand/Negotiation/blob/master/src/Negotiation/AbstractNegotiator.php#L56 AcceptHeader::getType() is used but doesn't necessary exists ...).
It may also be good to rename ``AcceptHeader`` to ``AcceptHeaderInterface`` or ``AcceptInterface``.

If you agree, I can make a pull request.

**Comment by neural-wetware** [comment]
The ``AcceptHeader`` interface seems redundant. All implementers already inherit from ``BaseAccept``, so isn't an interface logically implied? Could we just remove it entirely?

Already done in my branch ``remove_acceptheader``. Unit tests pass without modification.

**Comment by Ener-Getick** [comment]
I don't know, people may want to provide their own implementation. I think the best solution is to provide an interface and an abstract class.
People can use many interfaces but only one abstract class per class.

**Comment by neural-wetware** [comment]
So this would allow someone to use the ``Negotiator`` classes with their own custom ``Accept`` class? Makes sense.

You would also want ``AcceptHeader::getQuality()``, right?

**Comment by Ener-Getick** [comment]
Yes, it would be great.

**Comment by neural-wetware** [comment]
Well, it's up to @willdurand. I don't have a problem with this.

**Comment by willdurand** [comment]
I have to think about that. I don't really want to create many interfaces, just because it would be cool. The lib does one job, quite well, and it is not a common|expected use case to change its behavior.

**Comment by neural-wetware** [comment]
If that is the philosophy then it might make sense to remove all the interfaces and merge my ``remove_acceptheader`` branch.
