### ISSUE TITLE
Generic language negotiation is missing since 2.0

### ISSUE THREAD

**Issue by ruudk** [willdurand/Negotiation#76]
I don't know if this is an mistake or not but this merged PR https://github.com/willdurand/Negotiation/pull/65 is missing in 2.0.

``` php
$acceptLanguageHeader = 'fr-FR, en-US;q=0.8';
$priorities           = array('fr');
// should return 'fr'
```

**Comment by willdurand** [comment]
Hi! so this is what you tweeted me the other day, right? It has not been backported I'd say.

**Comment by ruudk** [comment]
Yep I tweet about that.

Would it be easy to have this back in? Because it has been fully rewritten.

**Comment by Hirbod** [comment]
will this ever get fixed?

**Comment by willdurand** [comment]
@Hirbod this should be fixed by https://github.com/willdurand/Negotiation/pull/96
