### ISSUE TITLE
LanguageNegociation fail with Safari (iOS9, Safari.9.1.1)

### ISSUE THREAD

**Issue by orykami** [willdurand/Negotiation#80]
Hi there !

We are encountering some troubles with LanguageNegociator under Safari.

Here's the Header sent by Safari on mobile & desktop : fr-fr

``` php
Accept-Language : fr-fr
```

``` php
$locale = $this->negotiator->getBest($request->getHeaderLine('Accept-Language'), $locales);
```

with 

``` php
$locales = ["fr", "en", "it", "de"]
```

$locale is NULL after that, or it should be fr right ?

Any ideas on what's the deal ?
Thank's !

**Comment by willdurand** [comment]
Hi! It seems related to #76

**Comment by Hirbod** [comment]
will this ever get fixed?

**Comment by willdurand** [comment]
Likely fixed by https://github.com/willdurand/Negotiation/pull/113
