### ISSUE TITLE
Regression in recent releases

### ISSUE THREAD

**Issue by willdurand** [willdurand/Negotiation#93]
Copy/paste from #92:

Hi @willdurand, @weierophinney! This PR and the new release (2.3) breaks our test suite on api-platform/core. See https://travis-ci.org/api-platform/core/jobs/228775063 for example.

I have this accept header: application/hal+json.
My priorities are:

[0] => "application/ld+json"
[1] => "application/hal+json"
[2] => "application/xml"
[3] => "text/xml"
[4] => "application/json"
[5] => "text/html"
Then, the AbstractNegotiator::getBest() method now returns application/ld+json instead of application/hal+json before.

It looks like something is not working properly here, nop? Thanks.

(Ping @dunglas)

**Comment by weierophinney** [comment]
I'm AFK until Monday, but will look at it first thing then; I suspect I
know what's happening and how to resolve it.
