### ISSUE TITLE
Language negotiator doesn't seem to work with IE and Edge

### ISSUE THREAD

**Issue by bbalet** [willdurand/Negotiation#97]
Internet Explorer and Edge send an `HTTP_ACCEPT_LANGUAGE` header equal to something like "fr-FR" that looks diferent from the format used by Chrome or Firefox, for example:
"fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3"

With Internet Explorer and Edge, your lib returns null on this call:

`$bestLanguage = $negotiator->getBest($_SERVER['HTTP_ACCEPT_LANGUAGE'], $languages);`

You may try on your side with this example: http://benjamin-balet.info/tauch/
Although the outcome may differ depending on your configuration.

**Comment by Hirbod** [comment]
I can confirm this. It doesn't work on Safari either, because HTTP_ACCEPT_LANGUAGE is empty...

**Comment by bbalet** [comment]
I realize this is a duplicate of #76
